import 'package:mma_promoter/data/models/models.dart';

/// Builds a fighter with every stat at [stat] unless individually
/// overridden. Keeps the test files readable now that a fighter carries
/// 23 fighting, 11 physical, 8 mental stats and 14 tendencies.
Fighter testFighter(
  String id, {
  int stat = 60,
  int? punching,
  int? kicking,
  int? power,
  int? speed,
  int? accuracy,
  int? defense,
  int? headMovement,
  int? blocking,
  int? footwork,
  int? takedowns,
  int? takedownDefense,
  int? wrestling,
  int? clinchStriking,
  int? clinchControl,
  int? clinchDefense,
  int? topControl,
  int? groundAndPound,
  int? guardRetention,
  int? sweeps,
  int? scrambling,
  int? submissionOffense,
  int? submissionDefense,
  int? grappling,
  int? cardio,
  int? durability,
  int? chin,
  int? bodyToughness,
  int? legToughness,
  int? strength,
  int? athleticism,
  int? recovery,
  int? explosiveness,
  int? flexibility,
  int? gripStrength,
  int? fightIq,
  int? composure,
  int? mentalAggression,
  int? discipline,
  int? confidence,
  int? heart,
  int? adaptability,
  int? killerInstinct,
  Tendencies? tendencies,
  FightingStyle style = FightingStyle.wellRounded,
  int age = 27,
  int popularity = 40,
  int morale = 80,
  int potential = 75,
  int winStreak = 2,
  int lossStreak = 0,
  int heightInches = 70,
  int reachInches = 70,
  InjuryStatus injuryStatus = InjuryStatus.healthy,
  bool retired = false,
  FightRecord record = const FightRecord(wins: 10, losses: 2),
  Contract? contract,
}) {
  return Fighter(
    id: id,
    name: id,
    age: age,
    nationality: 'USA',
    weightClass: WeightClass.lightweight,
    heightInches: heightInches,
    weightLbs: 155,
    reachInches: reachInches,
    record: record,
    fightingStats: FightingStats(
      punching: punching ?? stat,
      kicking: kicking ?? stat,
      power: power ?? stat,
      speed: speed ?? stat,
      accuracy: accuracy ?? stat,
      defense: defense ?? stat,
      headMovement: headMovement ?? stat,
      blocking: blocking ?? stat,
      footwork: footwork ?? stat,
      takedowns: takedowns ?? stat,
      takedownDefense: takedownDefense ?? stat,
      wrestling: wrestling ?? stat,
      clinchStriking: clinchStriking ?? stat,
      clinchControl: clinchControl ?? stat,
      clinchDefense: clinchDefense ?? stat,
      topControl: topControl ?? stat,
      groundAndPound: groundAndPound ?? stat,
      guardRetention: guardRetention ?? stat,
      sweeps: sweeps ?? stat,
      scrambling: scrambling ?? stat,
      submissionOffense: submissionOffense ?? stat,
      submissionDefense: submissionDefense ?? stat,
      grappling: grappling ?? stat,
    ),
    physicalStats: PhysicalStats(
      cardio: cardio ?? stat,
      durability: durability ?? stat,
      chin: chin ?? stat,
      bodyToughness: bodyToughness ?? stat,
      legToughness: legToughness ?? stat,
      strength: strength ?? stat,
      athleticism: athleticism ?? stat,
      recovery: recovery ?? stat,
      explosiveness: explosiveness ?? stat,
      flexibility: flexibility ?? stat,
      gripStrength: gripStrength ?? stat,
    ),
    mentalStats: MentalStats(
      fightIq: fightIq ?? stat,
      composure: composure ?? stat,
      aggression: mentalAggression ?? stat,
      discipline: discipline ?? stat,
      confidence: confidence ?? stat,
      heart: heart ?? stat,
      adaptability: adaptability ?? stat,
      killerInstinct: killerInstinct ?? stat,
    ),
    style: style,
    tendencies: tendencies ?? balancedTendencies,
    potential: potential,
    popularity: popularity,
    morale: morale,
    injuryStatus: injuryStatus,
    winStreak: winStreak,
    lossStreak: lossStreak,
    retired: retired,
    contract: contract,
  );
}

const balancedTendencies = Tendencies(
  strikingFrequency: 50,
  takedownFrequency: 50,
  kickFrequency: 50,
  clinchFrequency: 50,
  submissionAttempts: 50,
  groundAndPound: 50,
  positionControl: 50,
  standUpPreference: 50,
  wallWork: 50,
  aggression: 50,
  counterStriking: 50,
  headHunting: 50,
  bodyAttacks: 50,
  legAttacks: 50,
);

/// A fighter who only ever wants to strike — useful for isolating the
/// standing game in tests.
const pureStrikerTendencies = Tendencies(
  strikingFrequency: 95,
  takedownFrequency: 2,
  kickFrequency: 40,
  clinchFrequency: 5,
  submissionAttempts: 5,
  groundAndPound: 20,
  positionControl: 20,
  standUpPreference: 95,
  wallWork: 10,
  aggression: 60,
  counterStriking: 30,
  headHunting: 70,
  bodyAttacks: 25,
  legAttacks: 20,
);

/// A grinder: takes you down and rides position.
const grinderTendencies = Tendencies(
  strikingFrequency: 30,
  takedownFrequency: 95,
  kickFrequency: 10,
  clinchFrequency: 55,
  submissionAttempts: 15,
  groundAndPound: 30,
  positionControl: 90,
  standUpPreference: 10,
  wallWork: 70,
  aggression: 45,
  counterStriking: 20,
  headHunting: 40,
  bodyAttacks: 30,
  legAttacks: 10,
);

/// A ground striker: takes you down and hits you.
const groundStrikerTendencies = Tendencies(
  strikingFrequency: 35,
  takedownFrequency: 90,
  kickFrequency: 10,
  clinchFrequency: 45,
  submissionAttempts: 15,
  groundAndPound: 95,
  positionControl: 45,
  standUpPreference: 10,
  wallWork: 45,
  aggression: 65,
  counterStriking: 20,
  headHunting: 60,
  bodyAttacks: 30,
  legAttacks: 10,
);

/// A submission hunter: takes you down and chases the tap.
const submissionHunterTendencies = Tendencies(
  strikingFrequency: 25,
  takedownFrequency: 85,
  kickFrequency: 10,
  clinchFrequency: 40,
  submissionAttempts: 95,
  groundAndPound: 20,
  positionControl: 35,
  standUpPreference: 15,
  wallWork: 30,
  aggression: 45,
  counterStriking: 20,
  headHunting: 30,
  bodyAttacks: 25,
  legAttacks: 10,
);
