import 'dart:math';

/// Skin-tone categories the current headshot art covers. This is
/// deliberately a short, growing list — add a value here (and an asset
/// list below) each time a new set of art fills in a tone this game
/// doesn't have yet (pale, olive/Latino, East Asian, South Asian, ...).
/// There's no "everyone gets a portrait" assumption: most nationalities
/// have zero weight below and simply show the initial-letter avatar
/// until art exists for a tone that actually fits them.
enum SkinTone { deep, medium, tan }

/// Headshot art available for each tone, generated by
/// `scripts/slice_headshots` (see `assets/fighters/source/` for the
/// original sprite sheets) — v1 is a single 25-headshot pixel-art set,
/// classified by sampled skin brightness into three buckets.
const Map<SkinTone, List<String>> _headshotsByTone = {
  SkinTone.deep: [
    'assets/fighters/deep_01.png',
    'assets/fighters/deep_02.png',
    'assets/fighters/deep_03.png',
    'assets/fighters/deep_04.png',
    'assets/fighters/deep_05.png',
    'assets/fighters/deep_06.png',
    'assets/fighters/deep_07.png',
    'assets/fighters/deep_08.png',
  ],
  SkinTone.medium: [
    'assets/fighters/medium_01.png',
    'assets/fighters/medium_02.png',
    'assets/fighters/medium_03.png',
    'assets/fighters/medium_04.png',
    'assets/fighters/medium_05.png',
    'assets/fighters/medium_06.png',
    'assets/fighters/medium_07.png',
  ],
  SkinTone.tan: [
    'assets/fighters/tan_01.png',
    'assets/fighters/tan_02.png',
    'assets/fighters/tan_03.png',
    'assets/fighters/tan_04.png',
    'assets/fighters/tan_05.png',
    'assets/fighters/tan_06.png',
    'assets/fighters/tan_07.png',
    'assets/fighters/tan_08.png',
    'assets/fighters/tan_09.png',
    'assets/fighters/tan_10.png',
  ],
};

/// Per-nationality chance (0-100) of drawing a headshot from each
/// available tone. Weights for a nationality don't need to sum to 100 —
/// the remainder is the chance of no portrait yet, which is the norm for
/// any nationality this art set doesn't plausibly cover (there's no
/// meaningful population of, say, Black Russian or Black Polish fighters
/// in reality, so those nationalities simply stay at their current
/// initial-letter avatar rather than being force-fit into this set).
///
/// Nigeria/Cameroon get heavy coverage since this tone range is their
/// predominant population. USA, Brazil, South Africa, the Caribbean and
/// a couple of Western European nations get partial coverage reflecting
/// real Black/Afro-descended minorities within otherwise mixed rosters.
/// Every other nationality is intentionally absent from this table.
const Map<String, Map<SkinTone, double>> _nationalityToneWeights = {
  'Nigeria': {SkinTone.deep: 45, SkinTone.medium: 35, SkinTone.tan: 10},
  'Cameroon': {SkinTone.deep: 45, SkinTone.medium: 35, SkinTone.tan: 10},
  'South Africa': {SkinTone.deep: 20, SkinTone.medium: 20, SkinTone.tan: 10},
  'Cuba': {SkinTone.deep: 15, SkinTone.medium: 15, SkinTone.tan: 10},
  'Dominican Republic': {SkinTone.deep: 15, SkinTone.medium: 15, SkinTone.tan: 10},
  'Brazil': {SkinTone.deep: 10, SkinTone.medium: 10, SkinTone.tan: 10},
  'USA': {SkinTone.deep: 8, SkinTone.medium: 8, SkinTone.tan: 9},
  'France': {SkinTone.deep: 8, SkinTone.medium: 6, SkinTone.tan: 3},
  'England': {SkinTone.deep: 6, SkinTone.medium: 6, SkinTone.tan: 3},
  'Canada': {SkinTone.deep: 5, SkinTone.medium: 5, SkinTone.tan: 3},
};

/// Rolls a headshot asset path for a fighter of this [nationality], or
/// null if there's no art covering their likely appearance yet (the
/// common case — most nationalities have no weight in the table above).
String? rollHeadshot(String nationality, Random rng) {
  final weights = _nationalityToneWeights[nationality];
  if (weights == null) return null;

  final roll = rng.nextDouble() * 100;
  var cumulative = 0.0;
  for (final entry in weights.entries) {
    cumulative += entry.value;
    if (roll <= cumulative) {
      final pool = _headshotsByTone[entry.key]!;
      return pool[rng.nextInt(pool.length)];
    }
  }
  return null;
}
